# Set the base image to Ubuntu
FROM python:3.7

# Upgrade the pip
RUN pip install --upgrade pip
RUN pip install --upgrade setuptools

# Copy the current directory contents into the container at /app
WORKDIR /app
COPY . .

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

# Run app.py when the container launches
CMD ["python", "app.py"]